// Auto-generated from vendor/pjrt_c_api.h (PJRT_Api struct fields).
// All functions returning PJRT_Error*; PJRT_Error_Destroy/PJRT_Error_Message (void) are excluded.
#define PJRT_OCL_ERR_FN_LIST(V) \
  V(PJRT_Error_GetCode) \
  V(PJRT_Plugin_Initialize) \
  V(PJRT_Plugin_Attributes) \
  V(PJRT_Event_Destroy) \
  V(PJRT_Event_IsReady) \
  V(PJRT_Event_Error) \
  V(PJRT_Event_Await) \
  V(PJRT_Event_OnReady) \
  V(PJRT_Client_Create) \
  V(PJRT_Client_Destroy) \
  V(PJRT_Client_PlatformName) \
  V(PJRT_Client_ProcessIndex) \
  V(PJRT_Client_PlatformVersion) \
  V(PJRT_Client_Devices) \
  V(PJRT_Client_AddressableDevices) \
  V(PJRT_Client_LookupDevice) \
  V(PJRT_Client_LookupAddressableDevice) \
  V(PJRT_Client_AddressableMemories) \
  V(PJRT_Client_Compile) \
  V(PJRT_Client_DefaultDeviceAssignment) \
  V(PJRT_Client_BufferFromHostBuffer) \
  V(PJRT_DeviceDescription_Id) \
  V(PJRT_DeviceDescription_ProcessIndex) \
  V(PJRT_DeviceDescription_Attributes) \
  V(PJRT_DeviceDescription_Kind) \
  V(PJRT_DeviceDescription_DebugString) \
  V(PJRT_DeviceDescription_ToString) \
  V(PJRT_Device_GetDescription) \
  V(PJRT_Device_IsAddressable) \
  V(PJRT_Device_LocalHardwareId) \
  V(PJRT_Device_AddressableMemories) \
  V(PJRT_Device_DefaultMemory) \
  V(PJRT_Device_MemoryStats) \
  V(PJRT_Memory_Id) \
  V(PJRT_Memory_Kind) \
  V(PJRT_Memory_DebugString) \
  V(PJRT_Memory_ToString) \
  V(PJRT_Memory_AddressableByDevices) \
  V(PJRT_Executable_Destroy) \
  V(PJRT_Executable_Name) \
  V(PJRT_Executable_NumReplicas) \
  V(PJRT_Executable_NumPartitions) \
  V(PJRT_Executable_NumOutputs) \
  V(PJRT_Executable_SizeOfGeneratedCodeInBytes) \
  V(PJRT_Executable_GetCostAnalysis) \
  V(PJRT_Executable_OutputMemoryKinds) \
  V(PJRT_Executable_OptimizedProgram) \
  V(PJRT_Executable_Serialize) \
  V(PJRT_LoadedExecutable_Destroy) \
  V(PJRT_LoadedExecutable_GetExecutable) \
  V(PJRT_LoadedExecutable_AddressableDevices) \
  V(PJRT_LoadedExecutable_Delete) \
  V(PJRT_LoadedExecutable_IsDeleted) \
  V(PJRT_LoadedExecutable_Execute) \
  V(PJRT_Executable_DeserializeAndLoad) \
  V(PJRT_LoadedExecutable_Fingerprint) \
  V(PJRT_Buffer_Destroy) \
  V(PJRT_Buffer_ElementType) \
  V(PJRT_Buffer_Dimensions) \
  V(PJRT_Buffer_UnpaddedDimensions) \
  V(PJRT_Buffer_DynamicDimensionIndices) \
  V(PJRT_Buffer_GetMemoryLayout) \
  V(PJRT_Buffer_OnDeviceSizeInBytes) \
  V(PJRT_Buffer_Device) \
  V(PJRT_Buffer_Memory) \
  V(PJRT_Buffer_Delete) \
  V(PJRT_Buffer_IsDeleted) \
  V(PJRT_Buffer_CopyToDevice) \
  V(PJRT_Buffer_ToHostBuffer) \
  V(PJRT_Buffer_IsOnCpu) \
  V(PJRT_Buffer_ReadyEvent) \
  V(PJRT_Buffer_UnsafePointer) \
  V(PJRT_Buffer_IncreaseExternalReferenceCount) \
  V(PJRT_Buffer_DecreaseExternalReferenceCount) \
  V(PJRT_Buffer_OpaqueDeviceMemoryDataPointer) \
  V(PJRT_CopyToDeviceStream_Destroy) \
  V(PJRT_CopyToDeviceStream_AddChunk) \
  V(PJRT_CopyToDeviceStream_TotalBytes) \
  V(PJRT_CopyToDeviceStream_GranuleSize) \
  V(PJRT_CopyToDeviceStream_CurrentBytes) \
  V(PJRT_TopologyDescription_Create) \
  V(PJRT_TopologyDescription_Destroy) \
  V(PJRT_TopologyDescription_PlatformName) \
  V(PJRT_TopologyDescription_PlatformVersion) \
  V(PJRT_TopologyDescription_GetDeviceDescriptions) \
  V(PJRT_TopologyDescription_Serialize) \
  V(PJRT_TopologyDescription_Attributes) \
  V(PJRT_Compile) \
  V(PJRT_Executable_OutputElementTypes) \
  V(PJRT_Executable_OutputDimensions) \
  V(PJRT_Buffer_CopyToMemory) \
  V(PJRT_Client_CreateViewOfDeviceBuffer) \
  V(PJRT_Executable_Fingerprint) \
  V(PJRT_Client_TopologyDescription) \
  V(PJRT_Executable_GetCompiledMemoryStats) \
  V(PJRT_Memory_Kind_Id) \
  V(PJRT_ExecuteContext_Create) \
  V(PJRT_ExecuteContext_Destroy) \
  V(PJRT_Buffer_CopyRawToHost) \
  V(PJRT_AsyncHostToDeviceTransferManager_Destroy) \
  V(PJRT_AsyncHostToDeviceTransferManager_TransferData) \
  V(PJRT_Client_CreateBuffersForAsyncHostToDevice) \
  V(PJRT_AsyncHostToDeviceTransferManager_RetrieveBuffer) \
  V(PJRT_AsyncHostToDeviceTransferManager_Device) \
  V(PJRT_AsyncHostToDeviceTransferManager_BufferCount) \
  V(PJRT_AsyncHostToDeviceTransferManager_BufferSize) \
  V(PJRT_AsyncHostToDeviceTransferManager_SetBufferError) \
  V(PJRT_AsyncHostToDeviceTransferManager_AddMetadata) \
  V(PJRT_Client_DmaMap) \
  V(PJRT_Client_DmaUnmap) \
  V(PJRT_Client_CreateUninitializedBuffer) \
  V(PJRT_Client_UpdateGlobalProcessInfo) \
  V(PJRT_TopologyDescription_Deserialize) \
  V(PJRT_Client_CreateAliasBuffer) \
  V(PJRT_Client_FulfillAliasBuffer) \
  V(PJRT_LoadedExecutable_GetDeviceAssignment) \
  V(PJRT_Client_CreateErrorBuffer) \
  V(PJRT_AsyncHostToDeviceTransferManager_TransferLiteral) \
  V(PJRT_Buffer_CopyRawToHostFuture) \
  V(PJRT_Device_PoisonExecution) \
  V(PJRT_Device_CreateAsyncTrackingEvent) \
  V(PJRT_AsyncTrackingEvent_Destroy) \
  V(PJRT_Executable_GetCompileOptions) \
  V(PJRT_Buffer_DonateWithControlDependency) \
  V(PJRT_Event_Create) \
  V(PJRT_Event_Set) \
  V(PJRT_Device_GetAttributes) \
  V(PJRT_Client_Load) \
  V(PJRT_LoadedExecutable_AddressableDeviceLogicalIds) \
  V(PJRT_Buffer_Bitcast) \
  V(PJRT_Error_ForEachPayload) \
  V(PJRT_TopologyDescription_Fingerprint) \
  V(PJRT_Executable_ParameterMemoryKinds) \
  V(PJRT_Device_ClearMemoryStats) \
  V(PJRT_TopologyDescription_MakeCanonicalShapeForMemorySpace) \
  V(PJRT_TopologyDescription_GetMemorySpaceKindIds) \
  /* end */
